import { describe, expect, it } from "vitest";
import fixtures from "./lens.fixtures.json";
import { band, lensValue, type LensSettings } from "./lens";

// Generated by web/scripts/lens_fixtures.py from the Python implementation.
describe("lens port matches jev_diff.judge.run", () => {
  const lenses = fixtures.lenses as Record<string, LensSettings>;
  for (const [name, lens] of Object.entries(lenses)) {
    it(`agrees on every event under the ${name} lens`, () => {
      for (const c of fixtures.cases) {
        const exp = (c.expected as Record<string, { value: number; band: string }>)[name];
        expect(lensValue(c.judgments, lens)).toBeCloseTo(exp.value, 12);
        expect(band(c.judgments, lens)).toBe(exp.band);
      }
    });
  }
  it("covers every band", () => {
    const seen = new Set(fixtures.cases.map((c) => (c.expected as any).ordering.band));
    expect(seen.has("material") && seen.has("review") && seen.has("cosmetic")).toBe(true);
  });
});
