"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-22 21:53:46.645167
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def _sqlite() -> bool:
    return op.get_bind().dialect.name == "sqlite"


def _forward_fk():
    # rulesets.cloned_from_version_id points at a table created later.  SQLite
    # accepts the forward reference inline (and cannot ALTER one in); other
    # databases get it added once ruleset_versions exists.
    if _sqlite():
        return [sa.ForeignKeyConstraint(['cloned_from_version_id'], ['ruleset_versions.id'],
                                        name='fk_ruleset_cloned_from')]
    return []


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blobs',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sha256')
    )
    op.create_table('judgments',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=True),
    sa.Column('answer', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('judgments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judgments_question_id'), ['question_id'], unique=False)

    op.create_table('oems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('prompt_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oem_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['oem_id'], ['oems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oem_id', 'slug')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'slug')
    )
    op.create_table('model_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('variant_label', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'year')
    )
    op.create_table('rulesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('oem_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('cloned_from_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    *_forward_fk(),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['oem_id'], ['oems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob_sha256', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('model_year_id', sa.Integer(), nullable=True),
    sa.Column('detection', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('detection_status', sa.String(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blob_sha256'], ['blobs.sha256'], ),
    sa.ForeignKeyConstraint(['model_year_id'], ['model_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_blob_sha256'), ['blob_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_model_year_id'), ['model_year_id'], unique=False)

    op.create_table('ruleset_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruleset_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruleset_id', 'version')
    )
    if not _sqlite():
        op.create_foreign_key('fk_ruleset_cloned_from', 'rulesets', 'ruleset_versions',
                              ['cloned_from_version_id'], ['id'])
    with op.batch_alter_table('ruleset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ruleset_versions_content_hash'), ['content_hash'], unique=False)

    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('old_model_year_id', sa.Integer(), nullable=False),
    sa.Column('new_model_year_id', sa.Integer(), nullable=False),
    sa.Column('old_document_id', sa.Integer(), nullable=False),
    sa.Column('new_document_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_version_id', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('timeline_id', sa.Integer(), nullable=True),
    sa.Column('timeline_position', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['new_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['new_model_year_id'], ['model_years.id'], ),
    sa.ForeignKeyConstraint(['old_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['old_model_year_id'], ['model_years.id'], ),
    sa.ForeignKeyConstraint(['ruleset_version_id'], ['ruleset_versions.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparisons_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparisons_model_id'), ['model_id'], unique=False)

    op.create_table('parse_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sheet_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('relation_histogram', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('fatal_count', sa.Integer(), nullable=False),
    sa.Column('warn_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ruleset_version_id'], ['ruleset_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ruleset_version_id')
    )
    op.create_table('change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('sheet', sa.String(length=128), nullable=False),
    sa.Column('also_on', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('disposition', sa.String(length=32), nullable=True),
    sa.Column('order_affecting', sa.Boolean(), nullable=False),
    sa.Column('lens_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comparison_id', 'eid')
    )
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.create_index('ix_change_events_code', ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_comparison_id'), ['comparison_id'], unique=False)

    op.create_table('comparison_results',
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('payload_z', sa.LargeBinary(), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('usage', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('cache_hits', sa.Integer(), nullable=False),
    sa.Column('cache_misses', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('ruleset_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comparison_id')
    )
    op.create_table('exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('lens', sa.String(length=64), nullable=True),
    sa.Column('blob_sha256', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blob_sha256'], ['blobs.sha256'], ),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_comparison_id'), ['comparison_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('comparison_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_comparison_id'), ['comparison_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index('ix_jobs_status_id', ['status', 'id'], unique=False)

    op.create_table('parse_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parse_run_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('where', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['parse_run_id'], ['parse_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parse_warnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parse_warnings_parse_run_id'), ['parse_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _sqlite():
        op.drop_constraint('fk_ruleset_cloned_from', 'rulesets', type_='foreignkey')
    with op.batch_alter_table('parse_warnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parse_warnings_parse_run_id'))

    op.drop_table('parse_warnings')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_id')
        batch_op.drop_index(batch_op.f('ix_jobs_document_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_comparison_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_comparison_id'))

    op.drop_table('exports')
    op.drop_table('comparison_results')
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_events_comparison_id'))
        batch_op.drop_index('ix_change_events_code')

    op.drop_table('change_events')
    op.drop_table('parse_runs')
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparisons_model_id'))
        batch_op.drop_index(batch_op.f('ix_comparisons_created_at'))

    op.drop_table('comparisons')
    with op.batch_alter_table('ruleset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ruleset_versions_content_hash'))

    op.drop_table('ruleset_versions')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_model_year_id'))
        batch_op.drop_index(batch_op.f('ix_documents_blob_sha256'))

    op.drop_table('documents')
    op.drop_table('timelines')
    op.drop_table('rulesets')
    op.drop_table('model_years')
    op.drop_table('models')
    op.drop_table('brands')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    op.drop_table('app_settings')
    op.drop_table('users')
    op.drop_table('oems')
    with op.batch_alter_table('judgments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judgments_question_id'))

    op.drop_table('judgments')
    op.drop_table('blobs')
    # ### end Alembic commands ###
